port: 8080
baseURL: http://localhost:8080
title: Epigram Demo
database: inmemory
trustProxy: false
googleOIDC:
  clientId: ""
  clientSecret: ""
entryQuestions:
  - question: The best color
    answer: purple
