port: 8080
bind: 0.0.0.0
baseURL: http://localhost:8080
title: Epigram Demo
description: A place to record quotes.
database: inmemory
trustProxy: false
googleOIDC:
  clientId: ""
  clientSecret: ""
entryQuestions:
  - question: The best color
    answer: purple
